Repository kevinhartmann23/fitlit, pull requests merged in 2020-12, with the labels that each got.

#33 Add activityRepo, userActivty repo, and activity test file
  src/activityRepo.js
  src/userActivity.js
  test/activity-test.js
Labels: enhancement

#31 refactor previous files
  src/sleepRepo.js
  src/userHydration.js
  src/userSleep.js
  test/hydration-test.js
  test/sleep-test.js
  test/test-data.js
  test/users-test.js
Labels: enhancement

#34 Finalize sleep tests, refactored date sorting
  src/sleepRepo.js
  src/userActivity.js
  src/userHydration.js
  src/userSleep.js
  test/sleep-test.js
Labels: bug, enhancement

#37 added img files
  assets/imgs/empty-bed-grey.png
  assets/imgs/empty-bed-purple.png
  assets/imgs/login-man.png
  assets/imgs/logo-man.ico
  assets/imgs/logo.png
  assets/imgs/man-act.png
  assets/imgs/man-hydra.png
  assets/imgs/man-sleep.png
  assets/imgs/menu-icon.png
  assets/imgs/sneakers-grey.png
  assets/imgs/sneakers-red.png
  assets/imgs/water-glass-blue.png
  assets/imgs/water-glass-grey.png
Labels: enhancement

#38 Initial commit
  src/activityRepo.js
  src/index.html
  src/styles.css
Labels: enhancement

#40 Login page styled
  src/index.html
  src/styles.css
Labels: enhancement

#47 styling day and week info wrappers
  src/chartHelpers.js
  src/dataHelpers.js
  src/index.html
  src/styles.css
Labels: enhancement

#48 Feature/dom manipulation
  src/chartHelpers.js
  src/dataHelpers.js
  src/domHelpers.js
  src/index.html
  src/scripts.js
  src/styles.css
  src/userActivity.js
  src/userHydration.js
  src/userRepo.js
  src/userSleep.js
Labels: enhancement

#65 Add info card display
  src/chartHelpers.js
  src/dataHelpers.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#50 main-page finished
  assets/imgs/man-empty.png
  src/dataHelpers.js
  src/domHelpers.js
  src/index.html
  src/styles.css
Labels: enhancement

#66 Add blur effect to account card display
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#70 Feature/responsiveness
  data/users.js
  src/dataHelpers.js
  src/domHelpers.js
  src/index.html
  src/scripts.js
  src/styles.css
  src/user.js
Labels: enhancement

#72 Updated responsiveness
  assets/imgs/exit-inactive.png
  assets/imgs/exit-red.png
  src/domHelpers.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#74 Feature/dom manipulation
  src/index.html
  src/scripts.js
  src/userRepo.js
Labels: enhancement

#75 Initial styling
  src/index.html
  src/styles.css
Labels: enhancement

#86 Run linter on test files
  src/userActivity.js
  test/activity-test.js
Labels: enhancement

#88 Add final styling
  src/styles.css
Labels: enhancement

#87 CHART,DATA,DOM HELPER LINTER PASS
  src/chartHelpers.js
  src/dataHelpers.js
  src/domHelpers.js
Labels: enhancement

#90 Add chart styling
  src/chartHelpers.js
  src/domHelpers.js
Labels: duplicate

#94 Add minor data labeling changes
  .DS_Store
  src/dataHelpers.js
  src/domHelpers.js
Labels: enhancement
